### ISSUE TITLE
VM Bypass

### ISSUE THREAD

**Issue by dvl2014** [melotic/ThreateningYeti#10]
Hi, I am somewhat new to GitHub, I will be using this via Macbook through a VM I installed (Parallells). 
I just want to know is the ThreateningYeti the only program I need to install on my VM to run this VM bypass and no detect for keyboard/mouse?

**Comment by melotic** [comment]
You might need to install the VC++ redistributable, found here https://aka.ms/vs/16/release/vc_redist.x86.exe
