### ISSUE TITLE
Program Still Not Able To Run On VM!

### ISSUE THREAD

**Issue by dvl2014** [melotic/ThreateningYeti#13]
@melotic @scrub10rd dont know why last issue was closed it is not resolved! See my video:
https://youtu.be/pIoekfI62Z8

**Comment by melotic** [comment]
You are trying to launch LDB from chrome, and this is not supported. This issue is being tracked in #2 . In addition, LDB 2.06.03 isn't supported yet.

**Comment by stupid-doge** [comment]
which lockdown version support？ would you mind to give me an url？

**Comment by dvl2014** [comment]
Dude stop commenting so many times youre annoying everyone.


Sent from Yahoo Mail for iPhone


On Tuesday, March 31, 2020, 10:47 AM, stupid-doge <notifications@github.com> wrote:




which lockdown version support？ would you mind to give me an url？

**Comment by stupid-doge** [comment]
I’m so sorry. It is my first time to play GitHub&nbsp;



from&nbsp;qq&nbsp;email


------------------ Original ------------------
